

ServerEvents.genericLootTables(e => {
    let lts = [
        "minecraft:chests/abandoned_mineshaft",
        "minecraft:chests/ancient_city",
        "minecraft:chests/ancient_city_ice_box",
        "minecraft:chests/bastion_bridge",
        "minecraft:chests/bastion_hoglin_stable",
        "minecraft:chests/bastion_other",
        "minecraft:chests/bastion_treasure",
        "minecraft:chests/buried_treasure",
        "minecraft:chests/desert_pyramid",
        "minecraft:chests/end_city_treasure",
        "minecraft:chests/igloo_chest",
        "minecraft:chests/jungle_temple",
        "minecraft:chests/jungle_temple_dispenser",
        "minecraft:chests/nether_bridge",
        "minecraft:chests/pillager_outpost",
        "minecraft:chests/ruined_portal",
        "minecraft:chests/shipwreck_map",
        "minecraft:chests/shipwreck_supply",
        "minecraft:chests/shipwreck_treasure",
        "minecraft:chests/simple_dungeon",
        "minecraft:chests/spawn_bonus_chest",
        "minecraft:chests/stronghold_corridor",
        "minecraft:chests/stronghold_crossing",
        "minecraft:chests/stronghold_library",
        "minecraft:chests/underwater_ruin_big",
        "minecraft:chests/underwater_ruin_small",
        "minecraft:chests/woodland_mansion",
        "minecraft:chests/village/village_armorer",
        "minecraft:chests/village/village_butcher",
        "minecraft:chests/village/village_cartographer",
        "minecraft:chests/village/village_desert_house",
        "minecraft:chests/village/village_fisher",
        "minecraft:chests/village/village_fletcher",
        "minecraft:chests/village/village_mason",
        "minecraft:chests/village/village_plains_house",
        "minecraft:chests/village/village_savanna_house",
        "minecraft:chests/village/village_shepherd",
        "minecraft:chests/village/village_snowy_house",
        "minecraft:chests/village/village_taiga_house",
        "minecraft:chests/village/village_tannery",
        "minecraft:chests/village/village_temple",
        "minecraft:chests/village/village_toolsmith",
        "minecraft:chests/village/village_weaponsmith",

        "dungeons_arise_seven_seas:chests/corsair_corvette/corsair_corvette_barrels",
        "dungeons_arise_seven_seas:chests/corsair_corvette/corsair_corvette_normal",
        "dungeons_arise_seven_seas:chests/corsair_corvette/corsair_corvette_treasure",

        "dungeons_arise_seven_seas:chests/pirate_junk/pirate_junk_barrels",
        "dungeons_arise_seven_seas:chests/pirate_junk/pirate_junk_normal",
        "dungeons_arise_seven_seas:chests/pirate_junk/pirate_junk_supply",
        "dungeons_arise_seven_seas:chests/pirate_junk/pirate_junk_treasure",

        "dungeons_arise_seven_seas:chests/small_yacht/small_yacht_barrels",
        "dungeons_arise_seven_seas:chests/small_yacht/small_yacht_normal",
        "dungeons_arise_seven_seas:chests/small_yacht/small_yacht_treasure",

        "dungeons_arise_seven_seas:chests/unicorn_galleon/unicorn_galleon_barrels",
        "dungeons_arise_seven_seas:chests/unicorn_galleon/unicorn_galleon_normal",
        "dungeons_arise_seven_seas:chests/unicorn_galleon/unicorn_galleon_supply",
        "dungeons_arise_seven_seas:chests/unicorn_galleon/unicorn_galleon_treasure",

        "dungeons_arise_seven_seas:chests/victory_frigate/victory_frigate_barrels",
        "dungeons_arise_seven_seas:chests/victory_frigate/victory_frigate_normal_lower",
        "dungeons_arise_seven_seas:chests/victory_frigate/victory_frigate_normal_upper",
        "dungeons_arise_seven_seas:chests/victory_frigate/victory_frigate_supply",
        "dungeons_arise_seven_seas:chests/victory_frigate/victory_frigate_treasure",

        "dungeons_arise:abandoned_temple/abandoned_temple_entrance",
        "dungeons_arise:abandoned_temple/abandoned_temple_map",
        "dungeons_arise:abandoned_temple/abandoned_temple_top",
        "dungeons_arise:aviary/aviary_barrels",
        "dungeons_arise:aviary/aviary_normal",
        "dungeons_arise:aviary/aviary_treasure",
        "dungeons_arise:bandit_towers/bandit_towers_barrels",
        "dungeons_arise:bandit_towers/bandit_towers_gardens",
        "dungeons_arise:bandit_towers/bandit_towers_normal",
        "dungeons_arise:bandit_towers/bandit_towers_rooms",
        "dungeons_arise:bandit_towers/bandit_towers_supply",
        "dungeons_arise:bandit_towers/bandit_towers_treasure",
        "dungeons_arise:bandit_village/bandit_village_barrels",
        "dungeons_arise:bandit_village/bandit_village_normal",
        "dungeons_arise:bandit_village/bandit_village_supply",
        "dungeons_arise:bandit_village/bandit_village_tents",
        "dungeons_arise:bathhouse/bathhouse_barrels",
        "dungeons_arise:bathhouse/bathhouse_normal",
        "dungeons_arise:ceryneian_hind/ceryneian_hind_treasure",
        "dungeons_arise:fishing_hut/fishing_hut_barrels",
        "dungeons_arise:foundry/foundry_chains",
        "dungeons_arise:foundry/foundry_lava_pit",
        "dungeons_arise:foundry/foundry_normal",
        "dungeons_arise:foundry/foundry_passage_exterior",
        "dungeons_arise:foundry/foundry_passage_normal",
        "dungeons_arise:foundry/foundry_treasure",
        "dungeons_arise:giant_mushroom/red_giant_mushroom",
        "dungeons_arise:giant_mushroom/twin_giant_mushroom",
        "dungeons_arise:greenwood_pub/greenwood_pub_barrels_hallways",
        "dungeons_arise:greenwood_pub/greenwood_pub_barrels_normal",
        "dungeons_arise:greenwood_pub/greenwood_pub_normal",
        "dungeons_arise:heavenly_challenger/heavenly_challenger_normal",
        "dungeons_arise:heavenly_challenger/heavenly_challenger_supply",
        "dungeons_arise:heavenly_challenger/heavenly_challenger_theater",
        "dungeons_arise:heavenly_challenger/heavenly_challenger_treasure",
        "dungeons_arise:heavenly_conqueror/heavenly_conqueror_barrels",
        "dungeons_arise:heavenly_conqueror/heavenly_conqueror_normal",
        "dungeons_arise:heavenly_conqueror/heavenly_conqueror_treasure",
        "dungeons_arise:heavenly_rider/heavenly_rider_barrels",
        "dungeons_arise:heavenly_rider/heavenly_rider_normal",
        "dungeons_arise:heavenly_rider/heavenly_rider_treasure",
        "dungeons_arise:illager_campsite/illager_campsite_map",
        "dungeons_arise:illager_campsite/illager_campsite_supply",
        "dungeons_arise:illager_campsite/illager_campsite_tent",
        "dungeons_arise:illager_corsair/illager_corsair_barrels",
        "dungeons_arise:illager_corsair/illager_corsair_supply",
        "dungeons_arise:illager_corsair/illager_corsair_treasure",
        "dungeons_arise:illager_fort/illager_fort_barrels",
        "dungeons_arise:illager_fort/illager_fort_normal",
        "dungeons_arise:illager_fort/illager_fort_treasure",
        "dungeons_arise:illager_galley/illager_galley_barrels",
        "dungeons_arise:illager_galley/illager_galley_supply",
        "dungeons_arise:illager_galley/illager_galley_treasure",
        "dungeons_arise:illager_windmill/illager_windmill_barrels",
        "dungeons_arise:illager_windmill/illager_windmill_treasure",
        "dungeons_arise:infested_temple/infested_temple_room_bookshelf",
        "dungeons_arise:infested_temple/infested_temple_room_forge",
        "dungeons_arise:infested_temple/infested_temple_room_garden",
        "dungeons_arise:infested_temple/infested_temple_room_normal",
        "dungeons_arise:infested_temple/infested_temple_room_supply",
        "dungeons_arise:infested_temple/infested_temple_room_table",
        "dungeons_arise:infested_temple/infested_temple_top_treasure",
        "dungeons_arise:jungle_tree_house/jungle_tree_house_barrels",
        "dungeons_arise:jungle_tree_house/jungle_tree_house_normal",
        "dungeons_arise:jungle_tree_house/jungle_tree_house_treasure",
        "dungeons_arise:keep_kayra/keep_kayra_garden_normal",
        "dungeons_arise:keep_kayra/keep_kayra_garden_treasure",
        "dungeons_arise:keep_kayra/keep_kayra_library_normal",
        "dungeons_arise:keep_kayra/keep_kayra_library_treasure",
        "dungeons_arise:keep_kayra/keep_kayra_normal",
        "dungeons_arise:keep_kayra/keep_kayra_treasure",
        "dungeons_arise:lighthouse/lighthouse_top",
        "dungeons_arise:mechanical_nest/mechanical_nest_equipment",
        "dungeons_arise:mechanical_nest/mechanical_nest_normal",
        "dungeons_arise:mechanical_nest/mechanical_nest_supply",
        "dungeons_arise:mechanical_nest/mechanical_nest_treasure",
        "dungeons_arise:merchant_campsite/merchant_campsite_map",
        "dungeons_arise:merchant_campsite/merchant_campsite_supply",
        "dungeons_arise:merchant_campsite/merchant_campsite_tent",
        "dungeons_arise:mining_system/mining_system_barrels",
        "dungeons_arise:mining_system/mining_system_treasure",
        "dungeons_arise:monastery/monastery_barrels",
        "dungeons_arise:monastery/monastery_bridges",
        "dungeons_arise:monastery/monastery_map",
        "dungeons_arise:mushroom_house/mushroom_house_barrels",
        "dungeons_arise:mushroom_house/mushroom_house_normal",
        "dungeons_arise:mushroom_house/mushroom_house_treasure",
        "dungeons_arise:mushroom_mines/mushroom_mines_barrels",
        "dungeons_arise:mushroom_mines/mushroom_mines_ores",
        "dungeons_arise:mushroom_mines/mushroom_mines_tools",
        "dungeons_arise:mushroom_mines/mushroom_mines_treasure",
        "dungeons_arise:mushroom_village/mushroom_village_barrels",
        "dungeons_arise:mushroom_village/mushroom_village_treasure",
        "dungeons_arise:plague_asylum/plague_asylum_barrels",
        "dungeons_arise:plague_asylum/plague_asylum_cells",
        "dungeons_arise:plague_asylum/plague_asylum_normal",
        "dungeons_arise:plague_asylum/plague_asylum_potions",
        "dungeons_arise:plague_asylum/plague_asylum_storage",
        "dungeons_arise:plague_asylum/plague_asylum_treasure",
        "dungeons_arise:scorched_mines/scorched_mines_barrels",
        "dungeons_arise:scorched_mines/scorched_mines_housing",
        "dungeons_arise:scorched_mines/scorched_mines_hub",
        "dungeons_arise:scorched_mines/scorched_mines_normal",
        "dungeons_arise:scorched_mines/scorched_mines_treasure",
        "dungeons_arise:shiraz_palace/shiraz_palace_elite",
        "dungeons_arise:shiraz_palace/shiraz_palace_gardens",
        "dungeons_arise:shiraz_palace/shiraz_palace_library",
        "dungeons_arise:shiraz_palace/shiraz_palace_normal",
        "dungeons_arise:shiraz_palace/shiraz_palace_rooms",
        "dungeons_arise:shiraz_palace/shiraz_palace_supply",
        "dungeons_arise:shiraz_palace/shiraz_palace_towers",
        "dungeons_arise:shiraz_palace/shiraz_palace_treasure",
        "dungeons_arise:small_blimp/small_blimp_coal_storage",
        "dungeons_arise:small_blimp/small_blimp_redstone_chamber",
        "dungeons_arise:small_blimp/small_blimp_treasure",
        "dungeons_arise:small_prairie_house/small_prairie_house_barrels",
        "dungeons_arise:small_prairie_house/small_prairie_house_normal",
        "dungeons_arise:small_prairie_house/small_prairie_house_ruined",
        "dungeons_arise:thornborn_towers/thornborn_towers_barrels",
        "dungeons_arise:thornborn_towers/thornborn_towers_rooms",
        "dungeons_arise:thornborn_towers/thornborn_towers_top_rooms",
        "dungeons_arise:thornborn_towers/thornborn_towers_top_treasure",
        "dungeons_arise:typhon/typhon_treasure",
        "dungeons_arise:undead_pirate_ship/undead_pirate_ship_barrels",
        "dungeons_arise:undead_pirate_ship/undead_pirate_ship_enchants",
        "dungeons_arise:undead_pirate_ship/undead_pirate_ship_supply",
        "dungeons_arise:undead_pirate_ship/undead_pirate_ship_treasure",
        "dungeons_arise:mines_treasure_big",
        "dungeons_arise:mines_treasure_medium",
        "dungeons_arise:mines_treasure_small",

    ]

    let gun = [
        "tacz:m95",
        "tacz:ai_awp",
        "tacz:rpk",
        "tacz:m249",
        "tacz:m320",
        "tacz:rpg7",
        "tacz:m107",
        "tacz:m700",
        "tacz:m16a4",
        "tacz:hk_g3",
        "tacz:m16a1",
        "tacz:m4a1",
        "tacz:mk14",
        "tacz:hk416d",
        "mk16:m4urgi",
        "tacz:ak47",
        "tacz:sks_tactical",
        "tacz:aug",
        "mk16:aks74u",
        "tacz:aa12",
        "gz:sasg_12",
        "mk16:ak105",
        "tacz:scar_h",
        "tacz:scar_l",
        "tacz:vector45",
        "tacz:hk_mp5a5",
        "tacz:ump45",
        "qkl:lmg31",
        "tacz:p90",
        "tacz:qbz_95",
        "tacz:type_81",
        "tacz:p320",
        "tacz:cz75",
        "tacz:deagle_golden",
        "tacz:glock_17",
        "suffuse:python",
        "tacz:deagle",
        "qkl:csg19",
        "tacz:uzi",
        "tacz:m1911",
    ]

    let loot_json = []

    for (let i = 0; i < gun.length; i++) {
        loot_json.push({
            "type": "minecraft:item",
            "name": "dt:gun_schematic",
            "functions": [
                {
                    "function": "minecraft:set_nbt",
                    "tag": "{gunId: \"" + gun[i] + "\",display:{Lore:['{\"italic\":false,\"color\":\"white\",\"extra\":[{\"text\":\"\"},{\"color\":\"light_purple\",\"text\":\"枪械: " + gun[i] + "\"}],\"text\":\"\"}']}}"
                }
            ],
            "weight": 1
        })
    }

    for (let i = 0; i < lts.length; i++) {
        e.modify(lts[i], loot => {
            if (loot.pools.length > 0) {
                let poolArr = loot.pools.get(0).asJsonObject.get("entries").asJsonArray
                poolArr.addAll(loot_json)
            }
        })
    }
})