ServerEvents.recipes(e => {
    e.remove("minecraft:wooden_axe")
    e.remove("minecraft:wooden_shovel");
    e.remove("minecraft:wooden_pickaxe");
    e.remove("minecraft:wooden_hoe");
    e.remove("minecraft:wooden_sword");
    e.remove("minecraft:stone_axe");
    e.remove("minecraft:stone_pickaxe");
    e.remove("minecraft:stone_shovel");
    e.remove("minecraft:stone_hoe");
    e.remove("minecraft:stone_sword");
    e.remove("minecraft:iron_axe");
    e.remove("minecraft:iron_pickaxe");
    e.remove("minecraft:iron_shovel");
    e.remove("minecraft:iron_hoe");
    e.remove("minecraft:iron_sword");
    e.remove("minecraft:diamond_axe");
    e.remove("minecraft:diamond_pickaxe");
    e.remove("minecraft:diamond_shovel");
    e.remove("minecraft:diamond_hoe");
    e.remove("minecraft:diamond_sword");
    e.remove("minecraft:golden_axe");
    e.remove("minecraft:golden_pickaxe");
    e.remove("minecraft:golden_shovel");
    e.remove("minecraft:golden_hoe");
    e.remove("minecraft:golden_sword");
})